server:
  port: 8888 #实例的端口
spring:
  application:
    name: demo-config-server #应用名称
  profiles:
    active: native #使用本地文件系统存储配置信息
eureka:
  instance:
    prefer-ip=adress: true # 是否显示主机IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/