server:
  port: 8050 #实例的端口
eureka:
  instance:
    prefer-ip=adress: true # 是否显示主机IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
  application:
    name: demo-gateway-zuul #应用名称
zuul:
  routes:
    order-serviceId: demo-eureka-order
    path: /order/**
#  ingored-services: demo-eureka-user